### ISSUE TITLE
Angular 5?

### ISSUE THREAD

**Issue by k-schneider** [ngx-utils/cookies#2]
Will this library be updated to target Angular 5 at some point?

**Comment by antonbarada** [comment]
will be in near future

**Comment by siloor** [comment]
@thebarada Do I see correctly, that the version 3.0.0 on npm already supports angular 5? I'm just asking, because I don't see the changes in this repository. Thanks!

**Comment by antonbarada** [comment]
actually, we successfully use module with Angular 5
you can try and let me know if it is not

**Comment by siloor** [comment]
I think it would be good, but there is a problem after building the application. If I'm creating a project with server side rendering, and then building the application with aot (`ng build --prod --aot --sourcemap && ng build --prod --app universal --output-hashing=none`), I'm getting the following error when i'm running the nodejs server:

```/node_modules/@ngx-utils/cookies/src/cookies.service.js:1
(function (exports, require, module, __filename, __dirname) { import { Injectable } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.2Oh9 (/dist-server/main.bundle.js:1:19061)
```

On the internet there are a lot of sources, where they said, that this problem used to coming from the transpiling process. Don't you experience the same thing?

**Comment by lgoudriaan** [comment]
@siloor Did you find a solution to this error? I have the same error, and it's blocking my progress.

**Comment by siloor** [comment]
@lgoudriaan Sadly I didn't have the time. Also the repo is not up-to-date with the released npm package, so I needed to do a quick, but very ugly fix. I just copied the repo to my application and made it angular 5 compatible.

@thebarada Could you please push your latest changes on this repo, which are already available on npm (3.0.0)?

**Comment by lgoudriaan** [comment]
@thebarada can you please take a look at this issue?

**Comment by antonbarada** [comment]
hey folks
sorry for delay! I didn't have time to fix it

please update package to version `3.0.1` and let me know if you have other issues
