### ISSUE TITLE
Are the steps given in the guide complete?

### ISSUE THREAD

**Issue by abhijeet1403** [ngx-utils/cookies#4]
I'm getting this error while serving the server code

`ERROR { Error: StaticInjectorError[REQUEST]:
  StaticInjectorError(Platform: core)[REQUEST]:
    NullInjectorError: No provider for REQUEST!`

I followed all the steps in the readme but still the issue.

**Comment by antonbarada** [comment]
I've updated readme, please check it
and let me know if you'll have questions
