### ISSUE TITLE
Angular 6?

### ISSUE THREAD

**Issue by orestisioakeimidis** [ngx-utils/cookies#7]
Hello, any idea when will this library support Angular 6? Thanks in advance!

**Comment by dmlb** [comment]
`Package "@ngx-utils/cookies" has an incompatible peer dependency to "rxjs" (requires "^5.5.6", would install "6.2.1").
`
I don't see any imports from rxjs in the services though, maybe just removing or upping the peer dependency requirements is all it needs?

**Comment by SergiusSidorov** [comment]
I prepared changes for support Angular 6 and Angular Express Engine 6.
There is a pool request:: #8

**Comment by aescarcha** [comment]
The Module works "as is" for me using angular 6, getting the warnings though

**Comment by michael-lang** [comment]
It may work for some, but `ng update rxjs` does not work.  results in an error, not just a warning:

```
                  Package "@ngx-utils/cookies" has an incompatible peer dependency to "rxjs" (requires "^5.5.6", would install "6.3.3").
Incompatible peer dependencies found. See above.
```

**Comment by nisdec** [comment]
@thebarada Any news on this?

**Comment by cjablonski76** [comment]
similar issue when trying to upgrade to Angular 7. 

> Package "@ngx-utils/cookies" has an incompatible peer dependency to "@angular/core" (requires "^5.0.0" (extended), would install "7.1.1").
